// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import (
	"database/sql"
)

type Card struct {
	ID     string
	Front  string
	Back   string
	DeckID string
}

type Deck struct {
	ID    string
	Title sql.NullString
}
